### ISSUE TITLE
Shortcuts and Yoran-Oran

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1504] opened 2017-02-19 02:53 UTC
Shortcuts will not parse Yoran-Oran as a valid target due to the dash i believe. i have 2 trusts out, trion and yoran-oran, i can cast on trion but not yoran-oran.

after fervour testing koru-moru is the same. there are several trusts with dash's in their names.

**Comment by trv6** [comment] 2017-02-20 04:16
Isn't Yoran-Oran a Unity trust? //yoran-oran (uc) might work.
I'm able to cast Koru-moru with //koru-moru, and (for some reason) //korumoru.

**Comment by sebyg666** [comment] 2017-02-20 08:12
im refering to //haste koru-moru, same with yoran-oran, not casting the trust, casting the trust works fine. 

from original post: 
>  i have 2 trusts out, trion and yoran-oran, i can cast on trion but not yoran-oran.

>

**Comment by trv6** [comment] 2017-02-20 19:22
Oh, my mistake. 
After checking, I experience this issue as well. One strange thing that I noticed is that, even without shortcuts loaded, the game-client won't process an action from the chat input on a target with a hyphenated name unless the second name is capitalized.
e.g.
/ma cure koru-moru -- doesn't work
/ma cure koru-Moru -- works
/ma cure Koru-moru -- doesn't work
/ma cure Koru-Moru -- works

If shortcuts runs string.lower over the command at some point, this could be the cause.

**Comment by Byrth** [comment] 2017-02-21 18:04
This is fixed in a version update I just pushed to -dev (2.902). Hopefully it doesn't mess anything else up.

**Closed as completed by Byrth** 2017-02-21 18:04 UTC
