### ISSUE TITLE
Craft menu lockout

### ISSUE THREAD

**Issue by Headtatt** [Windower/Lua#1921] opened 2020-08-19 16:31 UTC
After turning on the support flag in the clothcraft house something breaks.  

Crafts already in the queue cannot execute.  Manual crafts will not execute.  While some items (like food) appear to let you use them, other items (like crystal clusters) return a "cannot be used on that target" message.  Cannot interact with NPCs, doors, or home points (as if their menus are being suppressed or another menu is invisibly locked open in the background).

Unloading or reloading the addon does not fix it.  Moving 100 yalms from the site of the error does not fix it.  Zoning DOES fix it, and makes executing a synth is possible again, but as aforementioned the home points cannot be used so this requires running to a zone exit.

Craft seems to behave normally as long as the support toggle is left off and I did not glitch getting support at other craft houses recently (leatherworking, and goldsmithing). I was also able to manually apply advanced support as normal, turn on the support flag, and craft until the buff wore and an attempt to rebuff with support caused the issue again.  I have not seen the addon successfully apply the image support buff any of the times I have reproduced the glitch, it fails prior to requesting it.

**Comment by Nifim** [comment] 2020-08-19 16:42
This sounds like craft is not properly handling the menu interaction, and results in a soft lock.

**Comment by RubenatorX** [comment] 2020-08-19 16:47
I believe this is a duplicate of
https://github.com/Windower/Lua/issues/1622

**Comment by joshk6656** [comment] 2020-08-19 17:00
I believe this is an issue because there are 2 support npcs in that zone and it is trying to click the wrong one (only if both are in memory).

Try logging out and back in at the NPC and see if it starts working (I bet it does).

If it does, go to line 234 of craft.lua and change:

local mob, npc = validate(support_npcs, true)

to

local mob, npc = validate(support_npcs, false)

You will now need to be within 6 of the advanced support NPC.

**Comment by joshk6656** [comment] 2020-08-19 17:08
This issue is resolved in the dev branch, will be fixed when someone does dev>live merge.

**Closed as completed by joshk6656** 2020-08-19 17:08 UTC
Labels: Type: Bug

**Comment by Headtatt** [comment] 2020-08-19 18:30
Can't logout, as the game will not act on any version of the logout command I have tried.  Menu, text command, etc. do not work to log out. 

With that said, editing line 234 and standing near the NPC is not glitching, so I suspect you are correct.
