### ISSUE TITLE
SpellCheck addon

### ISSUE THREAD

**Issue by nitrous24** [Windower/Lua#1377] opened 2015-11-18 21:49 UTC
The addon lists spells players don't have access to. Fairly certain there's a way to exclude them easily.

**Comment by DamienDennehy** [comment] 2015-11-18 21:56
That's by design?

SpellCheck's description is "This addon lists spells you haven't unlocked yet."

The idea behind it is that it'll list out any missing spells/trusts etc so you can go off and buy/quest them.

**Comment by nitrous24** [comment] 2015-11-18 22:01
No i mean, It lists things like DIaga 3 4 5 banishga 4 5, tier 4 and 5 of elemental -ga spells. Spells players cannot have access to.

**Comment by nitrous24** [comment] 2015-11-18 22:02
Some of these wouldn't be easy to not include, But some of them have no info in jobs table so they could be excluded that way

**Comment by DamienDennehy** [comment] 2015-11-18 22:13
Ah got it. Probably the easiest way is just to have an exclude file per category - I was already running into issues like excluding Unity Trusts anyway.

Are BG's Spell lists up to date? I'll use them as a baseline.

Ex https://www.bg-wiki.com/bg/White_Mage

**Comment by nitrous24** [comment] 2015-11-18 22:35
no they're not, they don't seem to include job point spells

**Comment by DamienDennehy** [comment] 2015-11-18 23:31
Okay I'll work on the filter functionality first and draft lists second.

**Comment by z16** [comment] 2015-11-19 05:48
For spells you can check it easily, just see if res.levels is an empty table:

``` lua
if command == 'spell' then
    spells_missing = spells_missing:filter(table.empty .. table.get-{'levels'})
end
```

Or, if you prefer standard syntax:

``` lua
if command == 'spell' then
    spells_missing = spells_missing:filter(functin(spell) return table.empty(spell.levels) end)
end
```

**Comment by alphaONE2** [comment] 2015-11-19 20:05
@DamienDennehy: Since you've turned on your issue tracker, I'm going to close this and cross link it to your issue tracker so you can close it when you're done.

**Closed as completed by alphaONE2** 2015-11-19 20:05 UTC
