### ISSUE TITLE
Attachment  set not saving

### ISSUE THREAD

**Issue by megamanxx00** [Windower/Lua#1336] opened 2015-08-02 12:55 UTC
Using Autocontrol add-on its not saving the attachment sets. it says it saves but when u log back in and try to pull up equipment set there r none listed

**Comment by nitrous24** [comment] 2015-08-09 00:41
Do you still have this issue? I don't understand what could possibly be wrong with yours. Last night i logged in for the first time in over a year and autocontrol worked fine for me. I was able to save the set, unload the addon and reload it and the set was still there.

**Comment by nitrous24** [comment] 2015-08-09 23:02
Going to close this, feel free to reopen and respond, but as i've said it worked fine for me and i can't really troubleshoot something that i can't reproduce.

**Closed as completed by nitrous24** 2015-08-09 23:02 UTC
