### ISSUE TITLE
Autojoin

### ISSUE THREAD

**Issue by Feary** [Windower/Lua#746] opened 2014-03-19 20:34 UTC
when logging out  i recieve an error   key is boolean

i will update the post when i get more info

**Comment by Feary** [comment] 2014-03-19 21:49
config.lua 162 attempt to index local 'key' ( a boolen value)

**Comment by z16** [comment] 2014-03-19 21:53
Can you show me your config file?

**Comment by Feary** [comment] 2014-04-06 19:32
http://pastebin.com/aKsZ7Kbm

**Comment by z16** [comment] 2014-04-30 05:32
Well, I tried my best to reproduce it and I just can't do it... are you sure you're not using outdated resources? Does it happen every time, or is it random?

**Comment by Sechs** [comment] 2014-04-30 06:36
It happens to me as well when I log and when I swap characters on the same account.
I get it on my mule as soon as I log and, strangely enough, once that happened I get it on my main once I return to it as well.

Also dunno if it's lag or not, but lately Autojoin sometimes doesn't join the party even if the person is in the whitelist.
This happens randomly and not methodically. Been happening since the previous (not the last) version update.

**Comment by z16** [comment] 2014-04-30 10:43
A new AutoJoin version was pushed yesterday that reworked some of the joining mechanics. Let me know if that's still an issue. Meanwhile I'll keep digging for this...

**Comment by Sechs** [comment] 2014-04-30 12:26
Another small thing (that makes no difference, it's just strange and was present even in older versions) is that sometimes Autojoin accepts the invite, you join the party, but the "received party invite" icon remain present. At that point you only have to type /join to make it disappear.
As far as I know it has no influence at all, it just feels/looks strange.

**Comment by z16** [comment] 2014-04-30 21:15
That is actually a vanilla FFXI flaw, if you `/join` too fast it will already send the join packet to the server before the icon was activated on your client, due to an delay I can't explain (SE likes random delays, as I'm sure you noticed). Unfortunately there's nothing AutoJoin can do about it, as it can't even detect that the icon is there. But as you observed it's really only cosmetic and has no impact on gameplay at all, so I'm not very concerned with it.

**Comment by Sechs** [comment] 2014-05-06 00:11
Worked flawlessly lately, didn't miss a single invite unless the person wasn't in my wlist.
Concerning the error on logout/shutdown that someone reported, it's an error on line 168 concerning something like "attempting to use 'lower'" returning a nil value or something like that.
Sorry for not being exact but it's very fast, hard to read :P

**Comment by z16** [comment] 2014-05-06 05:48
Unfortunately that doesn't help me much by itself... fyi though, if you do `//console_log 1` it will enable logging the console output to a file `Windower/console.log`, so you won't have to miss anything anymore. Can just enable it temporarily and disable it again afterwards, just so you get an accurate error message.

**Comment by Sechs** [comment] 2014-05-07 17:07
I don't get what triggers it, because it doesn't happen all the time, but when it does it happens on /logout (goin to mule) and /shutdown as well.
This is the exact error

"//addons/libs/config.lua:162: attempt to call method 'lower' (a nil value)"

**Comment by z16** [comment] 2014-05-09 17:23
I pushed a fix to dev earlier, I'm not sure if that was the only problem with it, but at least one of those errors should be fixed now. Closing this unless a new one pops up.

**Closed as completed by z16** 2014-05-09 17:23 UTC
Labels: Type: Bug, Status: Fixed, Category: Addon
