### ISSUE TITLE
[Addon][Treasury] - Auto-Drop unintended consequences with Auto-Pass

### ISSUE THREAD

**Issue by Turelyo** [Windower/Lua#2341] opened 2024-04-02 18:34 UTC
Consider the following loot pool:
```
[0] Behemoth Hide
[1] Behemoth Tongue
[2] Defending Ring
```

You have Behemoth Tongue configured to automatically be dropped. Treasury detects this, determines it should auto-pass on the Behemoth Tongue, and schedules a task to run after a random delay to pass on the item in the loot pool at index 1. But before that task can execute, the Behemoth Hide falls out of the loot pool naturally, leaving the loot pool as this:

```
[0] Behemoth Tongue
[1] Defending Ring
```

Thus, Treasury tells the server to pass on the Defending Ring (now at index 1). No one notices, and the kind folks who were helping you farm one pass on it so you can collect it. The Defending Ring then gets destroyed.

The problem:

This happens regardless of whether or not you have auto-pass or auto-drop enabled. Treasury is currently coded to not consider either of these settings when deciding if it should automatically pass on an item.

This is a true story. It happened to me a while ago. I've modified my local copy of the addon to completely disable the auto-pass functionality. The likelihood of this race condition happening is pretty low, but as I've personally experienced it can and does happen, sometimes with catastrophic results.

Proposed solutions:

1. Refresh the loot list within the scheduled task to auto-pass on an item, validate the item name at that index is the one intended
2. Make this functionality respect the auto-pass setting.

**Comment by RubenatorX** [comment] 2024-04-02 18:37
Duplicate of #2088

**Closed as completed by RubenatorX** 2024-04-02 18:37 UTC

**Comment by Turelyo** [comment] 2024-04-22 12:41
I respect that that issue may be similar to this one; however, it highlights some additional issues.  Namely, that auto-drop effects auto-pass even if auto-pass is disabled.  I'm happy to make a separate, distinct issue for that problem, but I wanted to make sure that didn't get missed due to the primary, more technical bug in the addon (which is duplicated by the issue you linked).

**Comment by RubenatorX** [comment] 2024-04-22 18:00
It's really not a different issue, it is just additional consequences of the same issue. You could have (and still can) add additional comments to the existing issue if you like.
